### ISSUE TITLE
early_stop in unsupervised.py?

### ISSUE THREAD

**Issue by zhwl2117** [weicy15/GCS#1]
Dear authors,

Thank you for your impressing work in graph self-supervised learning.

When I tried to run your codes, I found there was a package: **early_stop** not found in the unsupervised.py

Could you please provide guidence on how to address this issue? Thanks!

**Comment by LLMforScience** [comment]
I have the same question.

**Comment by hhh123hh3** [comment]
The same issue, looks like the code is incomplete, could you please fix the problem? Thanks

**Comment by weicy15** [comment]
Sorry for the delay of replying. I have uploaded the early_stop module in the repository.
